name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo a string
        id: pod
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: echo a string 2
        env:
          TEST: ${{ steps.pod.outputs }}
        run: |
          echo $TEST
      # - name: multiline script
      #   run: |
      #     node -v
      #     npm -v
      # - name: Sleep for 30 seconds
      #   run: sleep 10s
      #   shell: bash
      # - name: echo after delay
      #   run: echo "Hello After Delay"
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Start minikube
  #       uses: medyagh/setup-minikube@master
  #     - name: Try the cluster !
  #       run: kubectl get pods -A
  #     - name: Deploy to minikube
  #       run: make deploy-minikube
  #     - name: Test service URLs
  #       run: |
  #         minikube service list
  #         minikube service example --url
  #         echo "------------------opening the service------------------"
  #     - name: Get Deployments
  #       run: |
  #         kubectl config get-contexts
  #         kubectl get deployments
  #         kubectl get pods
